name: Deploy to GitHub-Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Installing Dependencies
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Building
        run: npm run prod

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FOLDER: ./dist
          BRANCH: gh-pages
          SINGLE_COMMIT: true
